In [192]:
from multiview import cpcmv as cpcmv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import naive_bayes, model_selection, metrics
import matplotlib.pyplot as plt
from sklearn.metrics import euclidean_distances
import re

import scipy.sparse.linalg as sparse


data_set = pd.read_excel('D:/Datasets/Banking.xlsx', header = 0)





In [193]:
genuine = data_set[data_set['Status']==0]
counterfeit = data_set[data_set['Status']==1]

genuine = genuine.loc[:,genuine.columns != 'Status']
counterfeit = counterfeit.loc[:,counterfeit.columns != 'Status']




In [194]:
genuine_cov = np.cov(genuine.T)
counterfeit_cov = np.cov(counterfeit.T)

In [195]:
t = np.array([genuine_cov,counterfeit_cov])

n = len(t[0])
np.array([n] * n)

#np.array([n] * t.shape[0])/np.sum(np.array([n] * t.shape[0]))

n_g = np.array([t.shape[1]] * t.shape[0])

n = n_g/np.sum(n_g)
n = len(t[0])

views = 2

n_num = np.array([n] * views)/np.sum(np.array([n] * views))
n_num

array([0.5, 0.5])

In [199]:
k = 4

t = np.array([genuine_cov,counterfeit_cov])
it = 15

def cpc(k,x):
    
    n = p = x.shape[1]
    
    views = len(x)

    n_num = np.array([n] * views)/np.sum(np.array([n] * views))


    D = np.zeros((k,views))
    Eigvec = np.zeros((p,k)) 
    
    pi = np.eye(p)

    s = np.zeros((p,p))
    it = 15
    

    #make a for loop for script
    for i in np.arange(views):
        s = s + (n_num[i] * x[i])
        
        
    e1,e2 = np.linalg.eigh(s)
    
    
    q0 = e2[:,::-1] 
    
    
    for i in np.arange(k):
        
        q = q0[:,i]
        q = np.array(q).reshape(len(q),1)
        d = np.zeros((1,views))
    
        for j in np.arange(views):
        
            d[:,j] = np.dot(np.dot(q.T,x[j]),q)
    
    
    
    
        for j in np.arange(it):
            s2 = np.zeros((p,p))
        
            for yy in np.arange(views):
                s2 = s2 + (n_num[yy]*np.sum(np.array([n] * views)) * x[yy] / d[:,yy])
         
        
            w = np.dot(s2,q) 
                
            w = np.dot(pi,w)
        
            q = w/ np.sqrt(np.dot(w.T,w))
        
            for yy in np.arange(views):
                
                d[:,yy] = np.dot(np.dot(q.T,x[yy]),q)
            
        D[i,:] = d
        Eigvec[:,i] = q[:,0]
        pi = pi - np.dot(q,q.T)


    return(Eigvec)
#print(D)  #eigenvalues

In [214]:
def cpc(k,x):
    
    n = p = x.shape[1]
    
    views = len(x)

    n_num = np.array([n] * views)/np.sum(np.array([n] * views))

    Eigvec = np.zeros((p,k)) 
    
    pi = np.eye(p)

    s = np.zeros((p,p))
    it = 15
    

    #make a for loop for script
    for i in np.arange(views):
        s = s + (n_num[i] * x[i])
        
        
    e1,e2 = np.linalg.eigh(s)
    
    
    q0 = e2[:,::-1] 
    
    
    for i in np.arange(k):
        
        q = q0[:,i]
        q = np.array(q).reshape(len(q),1)
        d = np.zeros((1,views))
    
        for j in np.arange(views):
        
            d[:,j] = np.dot(np.dot(q.T,x[j]),q)
     
    
        for j in np.arange(it):
            s2 = np.zeros((p,p))
        
            for yy in np.arange(views):
                s2 = s2 + (n_num[yy]*np.sum(np.array([n] * views)) * x[yy] / d[:,yy])
         
        
            w = np.dot(s2,q) 
                
            w = np.dot(pi,w)
        
            q = w/ np.sqrt(np.dot(w.T,w))
        
            for yy in np.arange(views):
                
                d[:,yy] = np.dot(np.dot(q.T,x[yy]),q)
            
        Eigvec[:,i] = q[:,0]
        pi = pi - np.dot(q,q.T)


    return(Eigvec)


In [204]:
it = 30
k = 6
cpc(k,t)

array([[ 6.04619850e-04, -3.68775504e-01,  3.32212702e-01,
         4.63777792e-01, -7.28022756e-01, -9.23688757e-02],
       [ 8.05815300e-03, -3.05693291e-01,  4.46111952e-01,
         1.15866236e-01,  3.35484880e-01,  7.62558663e-01],
       [ 2.02613240e-02, -3.79477730e-01,  3.53790081e-01,
         1.82146491e-01,  5.49486671e-01, -6.28733460e-01],
       [ 8.19592081e-01, -2.49559607e-01,  9.46819497e-02,
        -4.87367556e-01, -1.36359603e-01, -3.00512174e-02],
       [-5.56425122e-01, -5.18062777e-01, -2.15442301e-02,
        -6.31813842e-01, -1.46726474e-01, -2.86443704e-02],
       [ 1.34848374e-01, -5.43952069e-01, -7.45669230e-01,
         3.18734944e-01,  1.23994197e-01,  1.13767026e-01]])

In [207]:

#check this next week


from sklearn import datasets

iris = datasets.load_iris()
X = iris.data # we only take the first two features.
y = iris.target

tot = pd.DataFrame(data = np.c_[X,y], columns = iris['feature_names'] + ['target'])

setosa = tot[tot['target'] == 0]


versicolour = tot[tot['target'] == 1]

virginica = tot[tot['target'] == 2]


setosa_data = setosa.loc[:,setosa.columns != 'target']

versicolour_data = versicolour.loc[:,versicolour.columns != 'target']

virginica_data = virginica.loc[:,virginica.columns != 'target']


setosa_cov = np.cov(setosa_data.T)

versicolour_cov = np.cov(versicolour_data.T)

virginica_cov = np.cov(virginica_data.T)

t = np.array([setosa_cov,versicolour_cov,virginica_cov])

virginica_data.shape

(50, 4)

In [208]:
k = 4


j = cpc(k,t)

fit = cpcmv.MVCPC(k = 4).fit_transform(t)

comp = fit[1]

comp

array([[-0.74672561,  0.0911447 , -0.6286431 , -0.19723426],
       [-0.44232205, -0.79279726,  0.32883123,  0.26018019],
       [-0.47429412,  0.60227868,  0.54335749,  0.34215219],
       [-0.1476386 , -0.0206288 ,  0.44882124, -0.88109976]])

In [209]:
j

array([[-0.74672561,  0.0911447 , -0.6286431 , -0.19723426],
       [-0.44232205, -0.79279726,  0.32883123,  0.26018019],
       [-0.47429412,  0.60227868,  0.54335749,  0.34215219],
       [-0.1476386 , -0.0206288 ,  0.44882124, -0.88109976]])

In [212]:
k = 3
x = np.array([[[2, 1, 8], [4, 5, 6], [3, 7, 9]],
                      [[1, 4, 7], [2, 5, 8], [3, 6, 9]]])

bb = cpc(k,x)

fit4 = cpcmv.MVCPC(k = 3).fit_transform(x)


bb



array([[-0.45139369,  0.88875921, -0.07969196],
       [-0.55811719, -0.35088538, -0.75192065],
       [-0.69623914, -0.29493478,  0.65441923]])

In [213]:
fit4[1]

array([[-0.45139369,  0.88875921, -0.07969196],
       [-0.55811719, -0.35088538, -0.75192065],
       [-0.69623914, -0.29493478,  0.65441923]])